#
# AMLOGIC sw demux driver
#

obj-$(AMLOGIC_SWDEMUX_DVBCSA) += dvbcsa_bs_algo.o \
				dvbcsa_algo.o \
				dvbcsa_block.o \
				dvbcsa_bs_block.o \
				dvbcsa_bs_key.o \
				dvbcsa_bs_stream.o \
				dvbcsa_bs_transpose.o \
				dvbcsa_key.o \
				dvbcsa_stream.o 
