#! /bin/sh
#
# audio effect (Dolby Audio for Wireless Speakers) service
#
case "$1" in
    start)
    /sbin/daws_service /etc/Audio_Effect.xml &
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
