LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
LOCAL_PRELINK_MODULE:= false
LOCAL_ARM_MODE := arm
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES:= v4l2_test.c
LOCAL_CFLAGS+=-DANDROID_SLT
LOCAL_STATIC_LIBRARIES :=libcutils

LOCAL_CFLAGS +=-g
LOCAL_CPPFLAGS := -g

LOCAL_MODULE := slt-isp
include $(BUILD_EXECUTABLE)