#!/bin/sh
#
# Start web server....
#

case "$1" in
  start)
	printf "Starting web server: "
	boa &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping web server : "
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  netready|netup|netdown|netchange) ;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

