#!/bin/sh

# Weston
[ -d /run/wayland ] || mkdir -p /run/wayland
chmod 0700 /run/wayland

export XDG_RUNTIME_DIR=/run/wayland/

MESON_EGL=fbdev
if [ -f /etc/meson_egl.conf ];then
    MESON_EGL=`cat /etc/meson_egl.conf`
fi
if [ $MESON_EGL == "wayland_drm" ];then
    NAME=openvt
    START_PARAMTERS="-vf -c 4 -- /usr/bin/weston-launch --tty=/dev/tty4 -u root -- --backend=drm-backend.so --config=/etc/aml-weston.ini --log=/tmp/weston.log"
else
    NAME=weston
    START_PARAMTERS="--config=/etc/aml-weston.ini --backend=fbdev-backend.so --tty=1 --device=/dev/fb0 --idle-time=0 --log=/tmp/weston.log"
fi

DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid

case "$1" in
     start)
         echo "Starting weston..."
         start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON -- $START_PARAMTERS
         ;;
     stop)
         echo -n "Stopping weston..."
         if [ $MESON_EGL == "wayland_drm" ];then
             killall weston-launch
         fi
         start-stop-daemon -K -o -p $PIDFILE
         rm -f $PIDFILE
         ;;
     *)
         echo "Usage: $0 {start|stop|restart}"
         exit 1
esac
 
exit $?

