CUTILS_PROJDIR  := $(AML_COMMON_DIR)/cutils
CUTILS_OSS_LIC  := CLOSED
CUTILS_DEPENDS  := #Add dependencies here. E.g. PAL_DEPENDS := platform
CUTILS_BINARIES := usr/lib/libcutils.so usr/bin/logcat
CUTILS_ADD_SRC  := $(ROKU_OS_INCLUDE_DIRS)

$(eval $(call prep_proj,CUTILS,cutils,$(CUTILS_PROJDIR),$(CUTILS_ADD_SRC)))

LDFLAGS = $(addprefix -L, $(ROKU_3PARTY_LIB_DIRS))
CUTILS_MAKE_OPTIONS = \
	CC=$(CC) \
	CXX=$(CXX) \
	OUT_ROOT=$(CUTILS_MAKEDIR) \
	PORTING_KIT_OS=$(PORTING_KIT_OS) \
	LDFLAGS="$(LDFLAGS)" \
	PLATFORMDIR=$(PLATFORMDIR) \
	AML_COMMON_DIR=$(AML_COMMON_DIR) \
	ROKU_PORT_COMMON_DIR=$(ROKU_PORT_COMMON_DIR)

cutils-configure:
cutils-build:
	(PATH=$(CROSSTOOLS_BIN):$(PATH) \
	$(MAKE) -C $(CUTILS_PROJDIR) $(CUTILS_MAKE_OPTIONS) all)

cutils-install:
	$(MAKE) -C $(CUTILS_PROJDIR) DESTDIR=$(CUTILS_INSTDIR) $(CUTILS_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(CUTILS_DESTDIR) install

cutils-clean:
	[ -e $(CUTILS_PROJDIR)/Makefile ] && $(MAKE) -C $(CUTILS_PROJDIR) $(CUTILS_MAKE_OPTIONS) clean || true
	[ -e $(CUTILS_PROJDIR)/Makefile ] && $(MAKE) -C $(CUTILS_PROJDIR) $(CUTILS_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(CUTILS_DESTDIR) distclean || true
