all:
	-make -C libadpcm all
	-make -C libfaad all
	-make -C libpcm all	
install:
	-make -C libadpcm install
	-make -C libfaad install
	-make -C libpcm install	
clean:
	-make -C libadpcm clean
	-make -C libfaad clean
	-make -C libpcm clean		
