#!/bin/sh

u_disk_init()
{
mount -t configfs none /sys/kernel/config
mkdir /sys/kernel/config/usb_gadget/amlogic
cd /sys/kernel/config/usb_gadget/amlogic
echo 0x18D1 > idVendor
echo 0x4e26 > idProduct
mkdir strings/0x409
#Read out serial number, and configure to ADB
serialnumber=$(cat /proc/cmdline | sed -n 's/.*androidboot.serialno=\([0-9a-zA-Z]*\).*/\1/p')
if [ -z "$serialnumber" ] || [ "$serialnumber" = "1234567890" ]; then
  serialnumber="0123456789ABCDEF"
fi
echo $serialnumber > strings/0x409/serialnumber
echo amlogic > strings/0x409/manufacturer
echo p212 > strings/0x409/product
mkdir configs/amlogic.1
mkdir configs/amlogic.1/strings/0x409
echo mass_storage > configs/amlogic.1/strings/0x409/configuration
echo 500 > configs/amlogic.1/MaxPower
mkdir functions/mass_storage.mass_storage
ln -s functions/mass_storage.mass_storage configs/amlogic.1
echo /dev/udisk > /sys/kernel/config/usb_gadget/amlogic/functions/mass_storage.mass_storage/lun.0/file
echo ff400000.dwc2_a > /sys/kernel/config/usb_gadget/amlogic/UDC
}


udisk_partition_init()
{
#mount dir create
if [ ! -d "/udisk"  ]
then
    mkdir /udisk
fi

mount -t vfat /dev/udisk /udisk
if [ $? -ne 0 ]
then
mkfs.vfat /dev/udisk
mount -t vfat /dev/udisk /udisk
fi
}

case "$1" in
	start)
		  udisk_partition_init
		  u_disk_init &
		;;
	netready|netup|netdown|netchange)
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac
