#!/bin/sh
#
# Dolby security firmware decryption

DSD=/sbin/dolby_fw
case "$1" in
    start)
    if [ ! -d "/tmp/ds/" ]; then
        mkdir -p /tmp/ds/
    fi
	$DSD /usr/lib/alsa-lib/libdaws.so /tmp/ds/0x21_0x1234_0x1d.so
	;;
    *)
	echo "Usage: S91dsd {start}" >&2
	exit 1
	;;
esac
