LIBMS12_PROJDIR  := $(AML_COMMON_DIR)/libms12
LIBMS12_OSS_LIC  := CLOSED
LIBMS12_DEPENDS  := cutils #Add dependencies here. E.g. PAL_DEPENDS := platform
LIBMS12_BINARIES := usr/lib/libms12.so
LIBMS12_ADD_SRC  := $(ROKU_OS_INCLUDE_DIRS)

$(eval $(call prep_proj,LIBMS12,libms12,$(LIBMS12_PROJDIR),$(LIBMS12_ADD_SRC)))

LDFLAGS = $(addprefix -L, $(ROKU_3PARTY_LIB_DIRS))
LIBMS12_MAKE_OPTIONS = \
	CC=$(CC) \
	CXX=$(CXX) \
	OUT_ROOT=$(LIBMS12_MAKEDIR) \
	PORTING_KIT_OS=$(PORTING_KIT_OS) \
	LDFLAGS="$(LDFLAGS)" \
	PLATFORMDIR=$(PLATFORMDIR) \
	AML_COMMON_DIR=$(AML_COMMON_DIR) \
	ROKU_PORT_COMMON_DIR=$(ROKU_PORT_COMMON_DIR) \
	ROKU_PORT_DIR=$(ROKU_PORT_DIR)

libms12-configure:
libms12-build:
	(PATH=$(CROSSTOOLS_BIN):$(PATH) \
	$(MAKE) -C $(LIBMS12_PROJDIR) $(LIBMS12_MAKE_OPTIONS) all)

libms12-install:
	$(MAKE) -C $(LIBMS12_PROJDIR) DESTDIR=$(LIBMS12_INSTDIR) $(LIBMS12_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(LIBMS12_DESTDIR) install

libms12-clean:
	[ -e $(LIBMS12_PROJDIR)/Makefile ] && $(MAKE) -C $(LIBMS12_PROJDIR) $(LIBMS12_MAKE_OPTIONS) clean || true
	[ -e $(LIBMS12_PROJDIR)/Makefile ] && $(MAKE) -C $(LIBMS12_PROJDIR) $(LIBMS12_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(LIBMS12_DESTDIR) distclean || true
