diff -Nur uboot-repo.orig/bl33/v2015/Makefile uboot-repo/bl33/v2015/Makefile
--- uboot-repo.orig/bl33/v2015/Makefile	2019-07-01 08:39:41.666117552 +0800
+++ uboot-repo/bl33/v2015/Makefile	2019-07-01 08:50:05.871057029 +0800
@@ -246,8 +246,8 @@
 CROSS_COMPILE ?=
 endif
 
-CROSS_COMPILE ?= /opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/aarch64-none-elf-
-CROSS_COMPILE_T32 ?= /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-
+CROSS_COMPILE ?= aarch64-none-elf-
+CROSS_COMPILE_T32 ?= arm-none-eabi-
 export CROSS_COMPILE
 export CROSS_COMPILE_T32
 
diff -Nur uboot-repo.orig/bl33/v2019/Makefile uboot-repo/bl33/v2019/Makefile
--- uboot-repo.orig/bl33/v2019/Makefile	2019-07-01 08:39:43.038119617 +0800
+++ uboot-repo/bl33/v2019/Makefile	2019-07-01 08:50:26.311087792 +0800
@@ -249,7 +249,7 @@
 CROSS_COMPILE ?=
 endif
 
-CROSS_COMPILE ?=/opt/gcc-linaro-7.3.1-2018.05-i686_aarch64-elf/bin/aarch64-elf-
+CROSS_COMPILE ?=aarch64-elf-
 export CROSS_COMPILE
 
 KCONFIG_CONFIG	?= .config
