#!/bin/sh
#
# secure video firmware load
#

start() {
	printf "Running tee_hdcp: "
	tee_hdcp
}
stop() {
	killall tee_hdcp
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
