#############################################################
#
# aml utility
#
#############################################################
AML_UTIL_VERSION = 0.1
AML_UTIL_SITE = $(TOPDIR)/../vendor/amlogic/aml_commonlib/utils
AML_UTIL_SITE_METHOD = local

AML_UTIL_DEPENDENCIES += linux libusb

BCM := FALSE
RTK := FALSE
CYPRESS := FALSE

# AP6242 AP6269 AP62x8 not set
BCM_MODULES := bcm40181 bcm40183 bcm43458 bcm4354 bcm4356 bcm4358 AP6212 \
	AP6234 AP6255 AP6256 AP62x2 AP6335 AP6441 AP6181 AP6210 AP6330 AP6476 AP6493 AP6398 AP6236 AP6201

BCM_WIFI_MODULE = $(call qstrip,$(BR2_PACKAGE_WIFI_FW_WIFI_MODULE))

ifneq ($(filter $(BCM_WIFI_MODULE),$(BCM_MODULES)),)
	BCM := TRUE
endif

RTK_MODULES := 8189es 8189ftv 8192cu 8192du 8192eu 8192es 8723au 8723bu 8723bs  8723ds 8811au 8812au 8822bu 8188eu

ifneq ($(BR2_PACKAGE_RTK8188EU)$(BR2_PACKAGE_RTK8189ES)$(BR2_PACKAGE_RTK8189FTV)$(BR2_PACKAGE_RTK8192CU)$(BR2_PACKAGE_RTK8192DU)$(BR2_PACKAGE_RTK8192EU)$(BR2_PACKAGE_RTK8192ES)$(BR2_PACKAGE_RTK8723AU)$(BR2_PACKAGE_RTK8723BU)$(BR2_PACKAGE_RTK8723BS)$(BR2_PACKAGE_RTK8723DS)$(BR2_PACKAGE_RTK8822BU)$(BR2_PACKAGE_RTK8811AU)$(BR2_PACKAGE_RTK8812AU),)
	RTK := TRUE
endif

# cypress wifi
CYPRESS_MODULES := cyw43438 cyw43455

CYPRESS_WIFI_MODULE = $(call qstrip,$(BR2_PACKAGE_WIFI_FW_WIFI_MODULE))

ifneq ($(filter $(CYPRESS_WIFI_MODULE),$(CYPRESS_MODULES)),)
	CYPRESS := TRUE
endif

AML_UTIL_PRIV_FLAGS = $(TARGET_CFLAGS) -I$(STAGING_DIR)/usr/include -lusb-1.0

ifeq ($(BCM), TRUE)
	AML_UTIL_PRIV_FLAGS += -DBROADCOM_MODULES_PATH=/lib/modules/$(LINUX_VERSION_PROBED)/kernel/broadcom/wifi -DBROADCOM_CONFIG_PATH=/etc/wifi
endif

ifeq ($(RTK), TRUE)
	AML_UTIL_PRIV_FLAGS += -DRTK_WIFI_MODULE -DREALTEK_MODULES_PATH=/lib/modules/$(LINUX_VERSION_PROBED)/kernel/realtek/wifi
endif

ifeq ($(CYPRESS), TRUE)
	AML_UTIL_PRIV_FLAGS += -DCYPRESS_WIFI_MODULE=$(CYPRESS_WIFI_MODULE) -DCYPRESS_MODULES_PATH=/lib/modules/$(LINUX_VERSION_PROBED)/kernel/cypress/wifi -DCYPRESS_CONFIG_PATH=/etc/wifi
endif

ifneq ($(BR2_PACKAGE_MRVL_WIFIBT),)
	AML_UTIL_PRIV_FLAGS += -DMRVL_MODULES_PATH=/lib/modules/$(LINUX_VERSION_PROBED)/kernel/mrvl
endif

ifneq ($(BR2_PACKAGE_QUALCOMM_WIFI),)
	AML_UTIL_PRIV_FLAGS += -DQCA_MODULES_PATH=/lib/modules/$(LINUX_VERSION_PROBED)/kernel/qualcomm/wifi
endif


define AML_UTIL_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D) CFLAGS="$(AML_UTIL_PRIV_FLAGS)" all
endef

define AML_UTIL_INSTALL_TARGET_CMDS
	$(TARGET_CONFIGURE_OPTS) $(MAKE) CC=$(TARGET_CC) -C $(@D) install
	$(INSTALL) -D -m 755 $(AML_UTIL_PKGDIR)/S43sysname $(TARGET_DIR)/etc/init.d
	$(INSTALL) -D -m 755 $(AML_UTIL_PKGDIR)/get_sysname.sh $(TARGET_DIR)/etc/init.d
endef

$(eval $(generic-package))
