#!/bin/sh

data_ubi_handle()
{
  #get current platform
  platform=`cat /proc/device-tree/compatible`
  case ${platform} in
    "amlogic, axg")
      platform="axg"
      ;;
    *)
      platform=""
      ;;
  esac

  if [ "${platform}" = "axg" ]
  then
    data_mtd_number=$(cat /proc/mtd | grep  -E "data" | awk -F : '{print $1}' | grep -o '[0-9]\+')
  fi

  if ! uenv get factory-reset | grep -q 'value:\[1\]'; then
    mount | grep 'data' && echo "Already mounted" && return 0
    #mount dir create
    if [ ! -d "/data" ]
    then
      mkdir /data
    fi

    # sure ubi vol exist or not
    ubiattach /dev/ubi_ctrl -m ${data_mtd_number}
    if [ -c "/dev/ubi1_0" ]
    then
      data_vol_name=`cat /sys/class/ubi/ubi1_0/name`
      if [ "${data_vol_name}" = "data" ]
      then
        mount -t ubifs /dev/ubi1_0 /data
        return 0
      fi
    fi

    #get data size
    #    dataSize=`cat /proc/mtd |grep "data"|awk '{print $2}'`
    #    dataSize=`printf %d 0x$dataSize`
    #    dataSize=$(expr $(expr $dataSize \/ 1024) \/ 1024)
    #    let dataSize=dataSize-4 ###Reserved 5M###
  else
    uenv set factory-reset 0
  fi

  #mount data
  ubidetach -p /dev/mtd${data_mtd_number}
  ubiformat -y /dev/mtd${data_mtd_number}
  ubiattach /dev/ubi_ctrl -m ${data_mtd_number}
  #    ubimkvol /dev/ubi1 -s $dataSize"MiB" -N data
  ubimkvol /dev/ubi1 -m -N data
  mount -t ubifs /dev/ubi1_0 /data
}

data_ext4_handle()
{
  if ! uenv get factory-reset | grep -q 'value:\[1\]'; then
    mount | grep '/data type ext4' && echo "Already mounted" && return 0
    #mount dir create
    if [ ! -d "/data" ]; then
      mkdir /data
    fi

    mount -t ext4 /dev/data /data
    if [ $? -eq 0 ]; then
      return 0
    fi
  else
    uenv set factory-reset 0
  fi
  echo y | mkfs.ext4 /dev/data
  mount -t ext4 /dev/data /data
  return 0
}
