#!/bin/sh

NAME_WPA_SUP=wpa_supplicant
DAEMON_WPA_SUP=/usr/sbin/$NAME_WPA_SUP
PIDFILE_WPA_SUP=/var/run/$NAME_WPA_SUP.pid

NAME_HOSTAPD=hostapd
DAEMON_HOSTAPD=/usr/sbin/$NAME_HOSTAPD
PIDFILE_HOSTAPD=/var/run/$NAME_HOSTAPD.pid

NAME_DNSMASQ=dnsmasq
DAEMON_DNSMASQ=/usr/sbin/$NAME_DNSMASQ
PIDFILE_DNSMASQ=/var/run/$NAME_DNSMASQ.pid

NAME_DHCPCD=dhcpcd
DAEMON_DHCPCD=/sbin/$NAME_DHCPCD
PIDFILE_DHCPCD=/var/run/${NAME_DHCPCD}-wlan0.pid

RTK_FLAG_FILE=/etc/wifi/rtk_station_mode
RTK_WIFI_FLAG="NONE"
AP_NAME_FILE=/etc/wifi/ap_name
MULTI_WIFI=/usr/bin/multi_wifi_load_driver

function hostapd_conf(){
    while true
    do
        cat /sys/class/net/$1/address | sed 's/\://g' > /etc/wifi/ap_name
        if [ -f $AP_NAME_FILE ];then
            break
        fi
    done
    ap_name=$(cat /etc/wifi/ap_name)
    ssid=amlogic-audio-$ap_name
    password=12345678

    echo 0 > /etc/hostapd_temp.conf
    echo "interface=$1" > /etc/hostapd_temp.conf
    echo "driver=nl80211" >> /etc/hostapd_temp.conf
    echo "ctrl_interface=/var/run/hostapd" >> /etc/hostapd_temp.conf
    echo "ssid=${ssid}" >> /etc/hostapd_temp.conf
    echo "channel=6" >> /etc/hostapd_temp.conf
    echo "ieee80211n=1" >> /etc/hostapd_temp.conf
    echo "hw_mode=g" >> /etc/hostapd_temp.conf
    echo "ignore_broadcast_ssid=0"  >> /etc/hostapd_temp.conf
    #  echo "wpa=3" >> /etc/hostapd_temp.conf
    #  echo "wpa_passphrase=${password}" >> /etc/hostapd_temp.conf
    #  echo "wpa_key_mgmt=WPA-PSK" >> /etc/hostapd_temp.conf
    #  echo "wpa_pairwise=TKIP CCMP" >> /etc/hostapd_temp.conf
    #  echo "rsn_pairwise=CCMP" >> /etc/hostapd_temp.conf
}

function start_sta(){
    ifconfig wlan0 > /dev/null

    if [ $? -eq 0 ]; then
        cnt=1
        while [ $cnt -lt 20 ]; do
            status=$(wpa_cli status | grep wpa_state)
            status=${status##*wpa_state=}
            if [ "$status" = "COMPLETED" ];then
                $DAEMON_DHCPCD -x # exit other dhcpcd service
                start-stop-daemon -S -m -p $PIDFILE_DHCPCD -x $DAEMON_DHCPCD -- -f /etc/dhcpcd.conf
                break
            else
                cnt=$((cnt + 1))
                sleep 1
            fi
        done

        if [[ "${RTK_WIFI_FLAG}" == "TRUE" ]]
        then
            if [ ${cnt} -eq 20 ]
            then
                rm ${RTK_FLAG_FILE}
                sync
            fi
        fi
    fi
}

function move_skt()
{
    skt_board=$(cat /proc/device-tree/amlogic-dt-id)
    case ${skt_board} in
        "axg_a113d_skt_v1")
            exit 0
            ;;
        "axg_a113x_skt_v1")
            exit 0
            ;;
    esac
}

function init_wifi_env()
{
    killall $NAME_DNSMASQ
    killall $NAME_HOSTAPD
    killall $NAME_WPA_SUP
}


function hostapd_conf_pre()
{
    hostapd_conf $1
    start-stop-daemon -s -m -p $PIDFILE_HOSTAPD -b -x $DAEMON_HOSTAPD -- /etc/hostapd_temp.conf -e /etc/entropy.bin
    ifconfig $1 192.168.2.1
    start-stop-daemon -S -m -p $PIDFILE_DNSMASQ  -x $DAEMON_DNSMASQ  -- -i$1  --dhcp-option=3,192.168.2.1 --dhcp-range=192.168.2.50,192.168.2.200,12h -p100
}

function wifi_setup(){
    ifconfig wlan0 up > /dev/null
    ifconfig wlan0 > /dev/null

    if [ $? -eq 0 ]; then
        if [[ "$1" == "both" ]]
        then
            start-stop-daemon -S -m -p $PIDFILE_WPA_SUP -b -x $DAEMON_WPA_SUP -- -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf
            #iw wlan0 interface add wlan1 type managed
            #hostapd_conf_pre wlan1
        elif [[ "$1" == "station" ]]
        then
            start-stop-daemon -S -m -p $PIDFILE_WPA_SUP -b -x $DAEMON_WPA_SUP -- -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf
        elif [[ "$1" == "ap" ]]
        then
            hostapd_conf_pre wlan0
        fi
    fi

    if [[ "$1" == "both" || "$1" == "station" ]]
    then
        start_sta &
    fi
}

function rtk_wifi_ap()
{
    wifi_setup ap
}


function rtk_wifi_station()
{
    wifi_setup station
    if [ ! -f ${RTK_FLAG_FILE} ]
    then
        init_wifi_env
        rtk_wifi_ap
    fi

}

function wifi_rtk()
{
    if [ -f ${RTK_FLAG_FILE} ]  
    then
        rtk_wifi_station
    else
        rtk_wifi_ap
    fi
}

function wifi_start()
{
    move_skt

    init_wifi_env

    echo "start wifi station mode load driver and setup......"

    #if [[ "$1" == "both" || "$1" == "station" ]]
    #then
        $MULTI_WIFI station 1
    #else
        #$MULTI_WIFI ap 1
    #fi
    
    wifi_chip_id_vendor="/sys/bus/mmc/devices/sdio:0001/sdio:0001:1/vendor"
    wifi_chip_id=$(cat ${wifi_chip_id_vendor})
    case "${wifi_chip_id}" in
      0x02d0)
        wifi_setup both
        ;;
      0x024c)
        RTK_WIFI_FLAG="TRUE"
        wifi_rtk
        ;;
    esac
}

case "$1" in
    start)
        wifi_start 
        ;;
    stop)
        echo -n "Stopping supplicant..."
        start-stop-daemon -K -o -p $PIDFILE_WPA_SUP
        start-stop-daemon -K -o -p $PIDFILE_DNSMASQ
        start-stop-daemon -K -o -p $PIDFILE_DHCPCD
        start-stop-daemon -K -o -p $PIDFILE_HOSTAPD
        $MULTI_WIFI station 0
        $POWERCTL 0
        ;;
    netready|netup|netdown|netchange) ;;
    restart|reload)
        start-stop-daemon -K -s HUP -n wpa_supplicant
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

