#! /bin/sh

# Additional options that are passed to led ring sync

case "$1" in
    start)
    printf "Starting lightDaemon: "
    start-stop-daemon -S -m -p /var/run/lightDaemon.pid -b -x /sbin/lightDaemon
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
    stop)
    ;;
    restart)
    ;;
    netready|netup|netdown|netchange)
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|netready|netup|netdown|netchange}"
    exit 1
    ;;
esac