#!/bin/sh
#
# chrome
#

start() {
	printf "Starting chrome: "
	[ -d /tmp/chrome ] || mkdir -p /tmp/chrome	
        export GOOGLE_API_KEY="no"
        export GOOGLE_DEFAULT_CLIENT_ID="no"
        export GOOGLE_DEFAULT_CLIENT_SECRET="no"
        export XDG_RUNTIME_DIR=/run/wayland/
        export $(dbus-launch)
        /usr/bin/chromium-browser/chrome --no-sandbox --in-process-gpu --disable-es3-gl-context --user-data-dir=/tmp/chrome --kiosk --app=file:///var/www/amlogic.html &
	echo "OK"
}
stop() {
	printf "Stopping chrome: "
	killall chrome
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

